version: "3.9"
services:
  react_template:
    build: .
    ports:
     - "9090:9090"
    stdin_open: true
    volumes:
      - ./react-template:/usr/src/app/react-template
      - /usr/src/app/react-template/node_modules
